sonar.projectKey=WildInfo
sonar.projectName=WildInfo
sonar.projectVersion=1.0
sonar.sources=backend/app/,frontend/
sonar.language=py,js,html,css
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/tests/**,**/__pycache__/**,**/*.pyc
sonar.python.bandit.reportPaths=
